apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dify
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/douban/charts
    targetRevision: master
    path: charts/dify

    helm:
      values: |
        image:
          tag: "1.14.0-rc1"

        worker:
          extraEnv:
            - name: PUBSUB_REDIS_CHANNEL_TYPE
              value: "pubsub"

  destination:
    server: https://kubernetes.default.svc
    namespace: dify

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true