apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dify
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://douban.github.io/charts/
    chart: dify
    targetRevision: 0.9.1

    helm:
      values: |
        global:
          storageType: "local"
          extraBackendEnvs:
            - name: SECRET_KEY
              value: "my-secret-key"
            - name: STORAGE_TYPE
              value: "local"
            - name: FILESYSTEM_STORAGE_TYPE
              value: "local"
            - name: S3_ENABLED
              value: "false"

        api:
          image:
            tag: "1.14.0-rc1"

        web:
          image:
            tag: "1.14.0-rc1"

        worker:
          image:
            tag: "1.14.0-rc1"
          extraEnv:
            - name: PUBSUB_REDIS_CHANNEL_TYPE
              value: "pubsub"

        pluginDaemon:
          image:
            repository: langgenius/dify-plugin-daemon
            tag: "0.0.7"

        sandbox:
          image:
            repository: svcvit/dify-sandbox-py
            tag: "0.1.4"

        persistence:
          enabled: true
          size: 10Gi

        ingress:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: dify

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true