global:
  imageTag: "1.14.0"
  secretKey: "change-this-secret"
  storageType: local
  vectorStore: weaviate

api:
  enabled: true
  replicaCount: 1

web:
  enabled: true
  replicaCount: 1

worker:
  enabled: true
  replicaCount: 1

sandbox:
  enabled: true

weaviate:
  enabled: true

postgresql:
  enabled: true
  auth:
    username: dify
    password: dify
    database: dify

redis:
  enabled: true