apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dify
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://douban.github.io/charts/
    chart: dify
    targetRevision: 0.9.1
    helm:
      valueFiles:
        - dify/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dify

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true