global:
  storageClass: standard
  storageType: "local"

  image:
    tag: "1.14.0-rc1"

  extraBackendEnvs:
    - name: SECRET_KEY
      value: "replace-with-your-own-secret"

    - name: STORAGE_TYPE
      value: "local"

    - name: FILESYSTEM_STORAGE_TYPE
      value: "local"

    - name: S3_ENABLED
      value: "false"

api:
  image:
    tag: "1.14.0-rc1"

  podSecurityContext:
    fsGroup: 1000

web:
  image:
    tag: "1.14.0-rc1"

worker:
  image:
    tag: "1.14.0-rc1"

  podSecurityContext:
    fsGroup: 1000

  extraEnv:
    - name: PUBSUB_REDIS_CHANNEL_TYPE
      value: "pubsub"

pluginDaemon:
  image:
    tag: "1.14.0-rc1"

sandbox:
  image:
    repository: svcvit/dify-sandbox-py
    tag: "0.1.4"

persistence:
  enabled: true
  size: 10Gi

ingress:
  enabled: false